# CH2A - Activity 1

In [1]:
import numpy as np

np.random.seed(123)
a = np.random.randint(100,999,20)
print('My 20 integers are:', a)

ans = []
for i in a:
    if i%5 == 0:
        ans.append(i)
print(ans)

My 20 integers are: [610 465 482 422 198 842 117 695 206 223 669 314 837 196 213 738 147 173
 644 324]
[610, 465, 695]


# CH2A - Activity 2 (Solution 1)

In [3]:
import numpy as np
np.random.seed(123)

ans = []
while len(ans)<=5:
    a = np.random.randint(100,999,1)
    if a%7 == 0:
        ans.append(a)
        # print(a)
        
print(np.array(ans))

[[196]
 [147]
 [644]
 [308]
 [168]
 [917]]


# CH2A - Activity 2 (Solution 2)

In [6]:
import random

for num in range(5):
    print(random.randrange(105, 999, 7))

553
721
973
420
168


# CH2A - Activity 3

In [2]:
import numpy as np

x = np.random.standard_normal(size=(4,3))
x.dtype

dtype('float64')

# CH2A - Activity 4

In [4]:
import numpy as np

x = np.arange(2,5,0.1)
print(x[1::2])

[2.1 2.3 2.5 2.7 2.9 3.1 3.3 3.5 3.7 3.9 4.1 4.3 4.5 4.7 4.9]


# CH2B - Activity 1

In [14]:
import numpy as np
np.random.seed(2019)
n0 = np.random.uniform(-2,2,(2,3))
print('My n0 is:\n',n0)

n0_copy = n0
a = np.ones((1,3))
n1 = np.vstack((n0_copy,a))
print('My n1 is:\n',n1)

left,n2 = np.hsplit(n1,[2])
print('My LEFT is:\n',left)
print('My RIGHT is:\n',n2)

print('Does the split apply in-place of n1?\n Answer is NO! \n',n1)

My x matrix is:
 [[8 9 5 9]
 [6 3 3 6]
 [3 6 4 6]]
My x1 is updated like x:
 [[8 9 5 9]
 [6 3 3 6]
 [1 1 1 1]]
My x2 remains unchanged:
 [[8 9 5 9]
 [6 3 3 6]
 [3 6 4 6]]


# CH2B - Activity 2

In [7]:
x = np.random.randint(1,10,size=(3,4))
y = np.random.standard_normal(size=(3,1))
z = np.random.standard_normal(size=(4,1))

a1 = np.concatenate((x,y),axis=1)
print('Combine x,y horizontally \n',a1)

a2 = np.concatenate((x,z.T),axis=0)
print('Combine x,y vertically \n',a2)

Combine x,y horizontally 
 [[ 8.          4.          3.          5.          1.80445789]
 [ 8.          3.          5.          9.         -0.96555003]
 [ 1.          8.          4.          5.         -1.31648003]]
Combine x,y vertically 
 [[ 8.          4.          3.          5.        ]
 [ 8.          3.          5.          9.        ]
 [ 1.          8.          4.          5.        ]
 [-0.62578516 -0.32694623 -0.3082092   0.82711746]]


# CH2C - Activity 1

In [23]:
import numpy as np
np.random.seed(2019)
n0 = np.random.uniform(-2,2,6)
n1 = n0.reshape((2,3))
print(n1<0)
n1[n1<0]=0
print(n1)

[[False  True False]
 [False False  True]]
[[1.61392886 0.         0.49587985]
 [0.5515096  1.52199628 0.        ]]


# CH2D - Activity 1

In [49]:
import numpy as np
n0 = np.arange(1,11)
ind = np.arange(1,11,2)
print('My n0 is: \n',n0)
print('My even index is:\n',ind)
print('Corresponding elements in n0 are: \n',n0[ind])
print('Multiplying these elements by 1.5: \n',n0[ind]*1.5)

n0[ind] *= 3
print('My new n0 is: \n',n0)

n1 = np.sort(n0)[::-1]
print('My n1 is: \n',n1)

My n0 is: 
 [ 1  2  3  4  5  6  7  8  9 10]
My even index is:
 [1 3 5 7 9]
Corresponding elements in n0 are: 
 [ 2  4  6  8 10]
Multiplying these elements by 1.5: 
 [ 3.  6.  9. 12. 15.]
My new n0 is: 
 [ 1  6  3 12  5 18  7 24  9 30]
My n1 is: 
 [30 24 18 12  9  7  6  5  3  1]
